spring:
  datasource:
    url: jdbc:h2:mem:focusflowdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
